accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView, ProfileEditView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/', ProfileEditView.as_view(), name='profile')
]

idoHack/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('exercises/', include('challenges.urls')),
    path('', include('infomation.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en" style="height: 100%;">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

  <title>{% block title %}{% endblock title %} idoHack</title>
</head>

<body style="background-color: #efdfd6; height: 100%;">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>

  <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
    <!-- Symbols... -->
  </svg>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">
      <!-- Navbar content... -->
      <a class="navbar-brand " href="{%url 'index'%}">idoHack</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="{%url 'index'%}">トップページ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'list-exercises'%}">演習一覧</a>
            </li>
          </ul>

          <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{user.username}}
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{%url 'accounts:profile'%}">プロフィール</a></li>
              <li><a class="dropdown-item" href="">基本設定</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{%url 'accounts:logout'%}">ログアウト</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link">得点:{{user.total_score}}</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:signup'%}">新規登録</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'accounts:login'%}">ログイン</a>
          </li>
          {% endif %}   
          </ul>
    
        </div>
    </div>
  </nav>

  <div class="container shadow p-3" style="background-color: #fff2eb; min-height: 85%; position: relative;">
    {% block content %}{% endblock content%}
  </div>

  <div class="p-2" style="margin-top: 20px; margin-bottom: 10%; background-color: #c9b5aa; width: 100%;">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <!-- Left column content -->
          Left column<br>
          Left column<br>
        </div>
        <div class="col-md-6">
          <!-- Right column content -->
          Right column
        </div>
      </div>
    </div>
  </div>
</body>

</html>